### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by 0106WeiWeiDeng** [YuLab-SMU/MPO.db#4]
**cmds:** 
1) wget https://bioconductor.org/packages/release/data/annotation/src/contrib/MPO.db_0.99.7.tar.gz
2) R CMD INSTALL MPO.db_0.99.7.tar.gz

fail with same error when installing MPO.db with devtools::install_github("YuLab-SMU/MPO.db") 

**error info:**

* installing to library ‘/home/deng/R/x86_64-redhat-linux-gnu-library/4.3’
* installing *source* package ‘MPO.db’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package ‘MPO.db’
    finding HTML links ... done
    MPOALIAS                                html
    MPOANATOMY                              html
    MPOANCESTOR                             html
    MPOBASE                                 html
    MPOCHILDREN                             html
    MPODb-class                             html
    MPOMAPCOUNTS                            html
    MPOMGIDO                                html
    MPOMPDO                                 html
    MPOMPMGI                                html
    MPOOBSOLETE                             html
    MPOOFFSPRING                            html
    MPOPARENTS                              html
    MPOSYNONYM                              html
    MPOTERM                                 html
    MPO_dbconn                              html
    MPOmetadata                             html
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘MPO.db’:
 .onLoad failed in loadNamespace() for 'MPO.db', details:
  call: collect(., Inf)
  error: Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Error: loading failed
Execution halted
ERROR: loading failed

**Comment by huerqiang** [comment]
See [this](https://support.bioconductor.org/p/9154865/) or use the [local version of MPO.db and HPO.db](https://github.com/huerqiang/HPO.db_MPO.db)
